- name: download application code
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/{{component}}.zip
    dest: /tmp
- name: unzip application code
  ansible.builtin.unarchive:
    src: /tmp/{{component}}.zip
    dest: /app
    remote_src: yes