- name: deamon reload
  ansible.builtin.systemd_service:
    daemon_reload: true
- name: start and enable {{component}} service
  ansible.builtin.service:
    name: "{{component}}"
    state: restarted
    enabled: yes
